### PR TITLE
Remove Status key from response_headers as per the Rack protocol

### PR DESCRIPTION
**Pull request by janraasch**
see Rack::Lint, https://github.com/rack/rack/blob/master/lib/rack/lint.rb#L639.

### CODE REVIEW

**Comment by waterlink** [comment]
Hi @janraasch, thanks for PR.

Have you tried to use this in some application?

My concern is: what happens to the original Status application behind reverse proxy have returned? How it gets forwarded to the original client if you remove `Status` response header?

**Comment by janraasch** [comment]
Hi @waterlink,

yes, I am using this. I ran into problems when running my rails app in development mode, since `Rack::Lint` is then active by default, which is why I looked into this.

To answer your concern. I believe it gets forwarded correctly as we do pass down the status as the first array entry `target_response.status` in https://github.com/tolingo/rack-reverse-proxy/blob/feature/remove-status/lib/rack/reverse_proxy.rb#L97. So the app can hence set the real `"Status"` header correctly when returning the request to the client.

**Comment by waterlink** [comment]
LGTM then

**Comment by waterlink** [comment]
@janraasch thanks!

**Comment by waterlink** [comment]
Just pushed 0.9.1 to rubygems

**Comment by janraasch** [comment]
Great. Thank you!

**Pull request merged**
