### PR TITLE
Fix setting global options

### PR DESCRIPTION
**Pull request by jjb**
rebasing @knapo's #37

### CODE REVIEW

**Comment by jjb** [comment]
tests passed 💃 

i'm working on making the code a bit better and updating docs etc., standby...

**Comment by jjb** [comment]
okay @waterlink let me know what you think of my changes, changelog notes, and decision to move to 1.0 (because of semantic versioning behavior change).

if you like it, i'll write tests

/cc @knapo

**Comment by waterlink** [comment]
Looks good to me. If you see how to write a unit test for this change easily, please do!

**Comment by jjb** [comment]
🎉 tests

**Comment by waterlink** [comment]
Looks great!

**Pull request merged**
